Урок 1
AlexeyAfrosin/PopularLib pull request #1
Opened 2021-05-26 18:54 UTC by AlexeyAfrosin

2021-05-27 20:17 UTC, PeterBukhal-sovcombank requested changes

2021-05-27 20:17 UTC, PeterBukhal-sovcombank commented on app/src/main/java/com/afrosin/popularlib/presenter/MainPresenter.kt
> +class MainPresenter(private val view: MainView) {
@AlexeyAfrosin модель следует передать в конструкторе, что бы обеспечить возможность подмены для тестирования, а так же сделать эти зависимости недоступными для изменения из вне, то есть инкапсулировать их.

2021-05-27 20:17 UTC, PeterBukhal-sovcombank commented on app/src/main/java/com/afrosin/popularlib/view/MainView.kt
> +    fun setButtonText(btnIndex: Int, text: String)
@AlexeyAfrosin цель домашнего задания в том числе уйти от использования индексов, использование которых затрудняет добавление новых счетчиков, так как приводит к необходимости ссылаться на эти индексы как в представлении, так и в презентере. В данном случае лучшим решением будет сделать отдельные методы для отображения во вью и модификации счетчиков в презентере.

2021-05-31 14:38 UTC, AlexeyAfrosin commented on app/src/main/java/com/afrosin/popularlib/presenter/MainPresenter.kt
> +class MainPresenter(private val view: MainView) {
Так сделать можно, но тогда в View появится ссылка на модель. Верно ли это?

2021-05-31 16:11 UTC, PeterBukhal-sovcombank commented on app/src/main/java/com/afrosin/popularlib/presenter/MainPresenter.kt
> +class MainPresenter(private val view: MainView) {
@AlexeyAfrosin смотря что считать view.

2021-05-31 16:33 UTC, AlexeyAfrosin commented on app/src/main/java/com/afrosin/popularlib/presenter/MainPresenter.kt
> +class MainPresenter(private val view: MainView) {
В данном случае за View считаем MainView?

2021-06-27 09:16 UTC, merged