Lesson3
AlexeyAfrosin/PopularLib pull request #3
Opened 2021-06-03 14:54 UTC by AlexeyAfrosin

2021-06-08 08:46 UTC, PeterBukhal-sovcombank requested changes
Нужно переделать момент с передачей списка пользователей.

2021-06-08 08:46 UTC, PeterBukhal-sovcombank commented on app/src/main/java/com/afrosin/popularlib/model/GithubUsersRepo.kt
> +    fun getUsers(): Observable<GithubUser> {
в данном случае просто нужно вернуть весь список, пользователей одним списком, но `Observable.fromIterable()` превращает список в поток сигналов из каждого элемента списка. в этом случае правильней использовать `Single.just()`

2021-06-08 08:46 UTC, PeterBukhal-sovcombank commented on app/src/main/java/com/afrosin/popularlib/presenter/UsersPresenter.kt
> +        usersListPresenter.users.add(githubUser)
тут серьезная ошиюка в том, что элементы списка вставляются по одному, это не эффективно. Переделать так что бы они добавлялись списком.

2021-06-08 08:46 UTC, PeterBukhal-sovcombank commented on app/src/main/java/com/afrosin/popularlib/view/UsersFragment.kt
> +    private val vb by viewBinding(FragmentUsersBinding::bind)
по умолчанию тут и так BIND используется, таким образом можно просто `private val vb: FragmentUsersBinding by viewBinding()`

2021-06-08 14:31 UTC, AlexeyAfrosin commented on app/src/main/java/com/afrosin/popularlib/model/GithubUsersRepo.kt
> +    fun getUsers(): Observable<GithubUser> {
Поправил

2021-06-08 14:31 UTC, AlexeyAfrosin commented on app/src/main/java/com/afrosin/popularlib/presenter/UsersPresenter.kt
> +        usersListPresenter.users.add(githubUser)
Поправил

2021-06-08 14:31 UTC, AlexeyAfrosin commented on app/src/main/java/com/afrosin/popularlib/view/UsersFragment.kt
> +    private val vb by viewBinding(FragmentUsersBinding::bind)
Поправил

2021-06-09 08:39 UTC, PeterBukhal-sovcombank approved these changes

2021-06-09 08:39 UTC, PeterBukhal-sovcombank commented on app/src/main/java/com/afrosin/popularlib/presenter/UsersPresenter.kt
> +        usersRepo.getUsers().subscribe { githubUsers -> addUsers(githubUsers) }
Так же тут упущен важный момент про который мы говорили на вебинаре, это отмена цепочки в случае необходимости. В текущем виде этот момент не реализован, нужно использовать Disposable и отменить цепочку как минимум в методе презентера onDestroy.

2021-06-09 13:21 UTC, AlexeyAfrosin commented on app/src/main/java/com/afrosin/popularlib/presenter/UsersPresenter.kt
> +        usersRepo.getUsers().subscribe { githubUsers -> addUsers(githubUsers) }
Добавил Disposable

2021-06-27 09:16 UTC, merged